### ISSUE TITLE
create `pipe_publisher.py`

### ISSUE THREAD

**Issue by marionleborgne** [marionleborgne/cloudbrain#34]
@lambdaloop could you also document your work in the cloudbrain wiki? like start a tutorial on how to make a custom publisher maybe? I feel that would be a useful resource for people. Basically something synthesizing the conversation you had with @jnaulty today. Just a nice to have, after you've made the new publisher. Thanks!

**Comment by marionleborgne** [comment]
@lambdaloop how is it going for this one?

**Comment by lambdaloop** [comment]
I was planning on working on it tonight to have a pull request ready before tomorrow. 
Sorry for the delay...

**Comment by marionleborgne** [comment]
No worries, it's totally fine. Do it in your own time. Let me know if you need help with the publisher interface. Thanks for picking up this issue!

**Comment by lambdaloop** [comment]
Thanks Marion! I may message you if I'm confused as I implement it tonight. See you tomorrow!

**Comment by marionleborgne** [comment]
:+1:
