### ISSUE TITLE
npm install: No package.json

### ISSUE THREAD

**Issue by realitygaps** [marionleborgne/cloudbrain#55]
When trying to visualize data:

running 'npm install' in the 'cloudbrain/ui' subdirectory returns:

npm ERR! package.json  npm can't find a package.json file in your current directory

Where can i find the package.json file?

**Comment by realitygaps** [comment]
It seems the npm install is no longer required, the documentation is probably out of date.

**Comment by marionleborgne** [comment]
I'm closing this because the UI actually lives in separate repo. I need to cleanup this `frontend` folders and take them out. Sorry for the inconvenience.
