### ISSUE TITLE
No 60 Hz line filter on the OpenBCI 32 Bit board.

### ISSUE THREAD

**Issue by andrewjaykeller** [marionleborgne/cloudbrain#96]
The OpenBCI 32 bit board does not have a 60Hz line filter. This code is misleading because the filter will not have an effect.

``` python
  def enable_filters(self):
    """
    Adds a filter at 60hz to cancel out ambient electrical noise.
    """
    self.ser.write('f')
    self.filtering_data = True

  def disable_filters(self):
    self.ser.write('g')
    self.filtering_data = False
```

[Link to lines of code for issue](https://github.com/marionleborgne/cloudbrain/blob/master/cloudbrain/connectors/openbci/OpenBCIBoard.py#L103-L112)

**Comment by marionleborgne** [comment]
Closing old issues with broken links and related to the older code base.
